create table if not exists public.tb_usuarios (
  id_usuario bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  nome_usuario varchar(60) not null,
  matricula varchar(14) not null unique,
  status varchar(12) not null default 'ativo' check (status in ('ativo', 'inativo')),
  perfil smallint not null default 0 check (perfil in (0, 1, 2)),
  email varchar(120) not null unique,
  usuario varchar(60) unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tb_dispositivos_eletronicos (
  id_produto bigint generated by default as identity primary key,
  descricao varchar(60) not null unique,
  pontuacao integer not null check (pontuacao > 0),
  status varchar(15) not null default 'ativo' check (status in ('ativo', 'inativo')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tb_transacao (
  id_transacao bigint generated by default as identity primary key,
  data date not null default current_date,
  quantia integer not null check (quantia > 0),
  pontos integer not null check (pontos >= 0),
  status_transacao varchar(13) not null default 'ativo' check (status_transacao in ('ativo', 'cancelado')),
  desc_modelo varchar(100) not null,
  id_produto_fk bigint not null references public.tb_dispositivos_eletronicos(id_produto),
  id_usuario_fk bigint not null references public.tb_usuarios(id_usuario),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.tb_pontuacao (
  id_pontuacao bigint generated by default as identity primary key,
  pontuacao integer not null default 0 check (pontuacao >= 0),
  data date not null default current_date,
  ano integer not null check (ano between 2000 and 2100),
  mes integer not null check (mes between 1 and 12),
  id_usuario_tb_fk bigint not null references public.tb_usuarios(id_usuario) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_usuario_tb_fk, ano, mes)
);

create table if not exists public.auditoria (
  id bigint generated by default as identity primary key,
  usuario_id varchar(70),
  cpf varchar(14),
  acao varchar(15),
  tabela varchar(70),
  data_acao date not null default current_date,
  hora_acao time not null default localtime,
  antes_acao text,
  depois_acao text,
  actor_auth_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists tb_usuarios_auth_user_id_idx on public.tb_usuarios(auth_user_id);
create index if not exists tb_usuarios_perfil_idx on public.tb_usuarios(perfil);
create index if not exists tb_transacao_usuario_data_idx on public.tb_transacao(id_usuario_fk, data desc);
create index if not exists tb_transacao_produto_idx on public.tb_transacao(id_produto_fk);
create index if not exists tb_pontuacao_ranking_idx on public.tb_pontuacao(ano, mes, pontuacao desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_tb_usuarios_updated_at on public.tb_usuarios;
create trigger set_tb_usuarios_updated_at
before update on public.tb_usuarios
for each row execute function public.set_updated_at();

drop trigger if exists set_tb_dispositivos_updated_at on public.tb_dispositivos_eletronicos;
create trigger set_tb_dispositivos_updated_at
before update on public.tb_dispositivos_eletronicos
for each row execute function public.set_updated_at();

drop trigger if exists set_tb_pontuacao_updated_at on public.tb_pontuacao;
create trigger set_tb_pontuacao_updated_at
before update on public.tb_pontuacao
for each row execute function public.set_updated_at();

create or replace function public.current_profile_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id_usuario
  from public.tb_usuarios
  where auth_user_id = auth.uid()
  limit 1;
$$;

create or replace function public.current_perfil()
returns smallint
language sql
stable
security definer
set search_path = public
as $$
  select perfil
  from public.tb_usuarios
  where auth_user_id = auth.uid()
  limit 1;
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_perfil() in (1, 2), false);
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_perfil() = 2, false);
$$;

create or replace view public.v_ranking_mensal
as
select
  p.id_usuario_tb_fk as id_usuario,
  u.nome_usuario,
  p.ano,
  p.mes,
  p.pontuacao,
  make_date(p.ano, p.mes, 1) as mes_referencia
from public.tb_pontuacao p
join public.tb_usuarios u on u.id_usuario = p.id_usuario_tb_fk
where p.pontuacao > 0
  and u.status = 'ativo';

create or replace function public.registrar_transacao(
  p_id_produto bigint,
  p_id_usuario bigint,
  p_quantia integer,
  p_data date,
  p_desc_modelo text,
  p_status text default 'ativo'
)
returns table (
  id_transacao bigint,
  pontos integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_id bigint;
  v_actor_nome text;
  v_actor_cpf text;
  v_actor_perfil smallint;
  v_produto record;
  v_total integer;
  v_year integer;
  v_month integer;
begin
  if auth.uid() is null then
    raise exception 'Usuario nao autenticado.';
  end if;

  select id_usuario, nome_usuario, matricula, perfil
  into v_actor_id, v_actor_nome, v_actor_cpf, v_actor_perfil
  from public.tb_usuarios
  where auth_user_id = auth.uid()
    and status = 'ativo';

  if v_actor_id is null then
    raise exception 'Perfil do usuario nao encontrado.';
  end if;

  if v_actor_perfil = 0 and p_id_usuario <> v_actor_id then
    raise exception 'Participantes so podem registrar transacoes para si mesmos.';
  end if;

  if p_quantia is null or p_quantia <= 0 then
    raise exception 'A quantidade deve ser maior que zero.';
  end if;

  select id_produto, descricao, pontuacao
  into v_produto
  from public.tb_dispositivos_eletronicos
  where id_produto = p_id_produto
    and status = 'ativo';

  if v_produto.id_produto is null then
    raise exception 'Dispositivo nao encontrado ou inativo.';
  end if;

  if not exists (
    select 1
    from public.tb_usuarios
    where id_usuario = p_id_usuario
      and status = 'ativo'
  ) then
    raise exception 'Participante nao encontrado ou inativo.';
  end if;

  v_total := v_produto.pontuacao * p_quantia;
  v_year := extract(year from p_data)::integer;
  v_month := extract(month from p_data)::integer;

  insert into public.tb_transacao (
    data,
    quantia,
    pontos,
    status_transacao,
    desc_modelo,
    id_produto_fk,
    id_usuario_fk,
    created_by
  )
  values (
    p_data,
    p_quantia,
    v_total,
    coalesce(p_status, 'ativo'),
    left(p_desc_modelo, 100),
    p_id_produto,
    p_id_usuario,
    auth.uid()
  )
  returning tb_transacao.id_transacao, tb_transacao.pontos
  into id_transacao, pontos;

  insert into public.tb_pontuacao (
    pontuacao,
    data,
    ano,
    mes,
    id_usuario_tb_fk
  )
  values (
    v_total,
    p_data,
    v_year,
    v_month,
    p_id_usuario
  )
  on conflict (id_usuario_tb_fk, ano, mes)
  do update set
    pontuacao = public.tb_pontuacao.pontuacao + excluded.pontuacao,
    data = excluded.data,
    updated_at = now();

  insert into public.auditoria (
    usuario_id,
    cpf,
    acao,
    tabela,
    depois_acao,
    actor_auth_user_id
  )
  values (
    v_actor_nome,
    v_actor_cpf,
    'Insercao',
    'tb_transacao',
    concat(
      'Produto: ', v_produto.descricao,
      ' | Quantidade: ', p_quantia,
      ' | Pontos: ', v_total,
      ' | Participante: ', p_id_usuario
    ),
    auth.uid()
  );

  return next;
end;
$$;

alter table public.tb_usuarios enable row level security;
alter table public.tb_dispositivos_eletronicos enable row level security;
alter table public.tb_transacao enable row level security;
alter table public.tb_pontuacao enable row level security;
alter table public.auditoria enable row level security;

drop policy if exists "profiles_select_own_or_staff" on public.tb_usuarios;
create policy "profiles_select_own_or_staff"
on public.tb_usuarios
for select
using (auth_user_id = auth.uid() or public.is_staff());

drop policy if exists "profiles_insert_own_participant" on public.tb_usuarios;
create policy "profiles_insert_own_participant"
on public.tb_usuarios
for insert
with check (auth_user_id = auth.uid() and perfil = 0 and status = 'ativo');

drop policy if exists "profiles_update_own_or_admin" on public.tb_usuarios;
create policy "profiles_update_own_or_admin"
on public.tb_usuarios
for update
using (auth_user_id = auth.uid() or public.is_admin())
with check (
  public.is_admin()
  or (
    auth_user_id = auth.uid()
    and perfil = public.current_perfil()
    and status = 'ativo'
  )
);

drop policy if exists "devices_select_active" on public.tb_dispositivos_eletronicos;
create policy "devices_select_active"
on public.tb_dispositivos_eletronicos
for select
using (status = 'ativo' or public.is_staff());

drop policy if exists "devices_staff_manage" on public.tb_dispositivos_eletronicos;
create policy "devices_staff_manage"
on public.tb_dispositivos_eletronicos
for all
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "transactions_select_own_or_staff" on public.tb_transacao;
create policy "transactions_select_own_or_staff"
on public.tb_transacao
for select
using (id_usuario_fk = public.current_profile_id() or public.is_staff());

drop policy if exists "scores_select_own_or_staff" on public.tb_pontuacao;
create policy "scores_select_own_or_staff"
on public.tb_pontuacao
for select
using (id_usuario_tb_fk = public.current_profile_id() or public.is_staff());

drop policy if exists "audit_admin_select" on public.auditoria;
create policy "audit_admin_select"
on public.auditoria
for select
using (public.is_admin());

grant usage on schema public to anon, authenticated;
grant select on public.tb_dispositivos_eletronicos to anon, authenticated;
grant select, insert, update on public.tb_usuarios to authenticated;
grant select on public.tb_transacao to authenticated;
grant select on public.tb_pontuacao to authenticated;
grant select on public.v_ranking_mensal to anon, authenticated;
grant execute on function public.registrar_transacao(bigint, bigint, integer, date, text, text) to authenticated;
